test

diff --git a/.github/workflows/build-browser.yml b/.github/workflows/build-browser.yml
--- a/.github/workflows/build-browser.yml
+++ b/.github/workflows/build-browser.yml
@@ -29,7 +29,7 @@ jobs:
       - name: Setup Emscripten
         uses: mymindstorm/setup-emsdk@v14
         with:
-          version: "3.1.73"
+          version: "3.1.74"
 
       - name: Get vcpkg commit ID
         id: vcpkg-step
@@ -72,11 +72,14 @@ jobs:
             -DVCPKG_BUILD_TYPE=${{ matrix.cmake_build_type }} \
             -DCMAKE_MAKE_PROGRAM=ninja \
             -DOPTIONS_ENABLE_IPO=OFF \
+            -DTOGGLE_BIN_FOLDER=ON \
             -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} \
-            -DTOGGLE_BOT_PROTECTION=OFF
+            -DTOGGLE_BOT_PROTECTION=OFF \
+            -DSPEED_UP_BUILD_UNITY=OFF
 
-      - name: Build
-        run: cmake --build build-${{ matrix.buildtype }}
+      - name: Build with Verbose Output
+        run: |
+          cmake --build build-${{ matrix.buildtype }} --target otclient --verbose || { echo "Build failed"; exit 1; }
 
       - name: List Build Directory Contents
         run: |
@@ -88,5 +91,4 @@ jobs:
         with:
           name: otclient-${{ matrix.buildtype }}-${{ github.sha }}
           path: |
-            ${{ github.workspace }}/build-${{ matrix.buildtype }}/*.{wasm,js,html}
-            ${{ github.workspace }}/build-${{ matrix.buildtype }}/**/*.{wasm,js,html}
+            ${{ github.workspace }}/build-${{ matrix.buildtype }}/bin/*.{wasm,js,html}
